//.rest File with Routes

GET https://project2-ybyn.onrender.com

### Get all contacts
GET https://project2-ybyn.onrender.com/movies

### Get contact by id , 1
GET https://project2-ybyn.onrender.com/movies/65f8c770a1f8cb4909bf4a14

### Get contact by id,  2
GET https://project2-ybyn.onrender.com/movies/65f8c770a1f8cb4909bf4a15

### Get contact by id , 3
GET https://project2-ybyn.onrender.com/movies/65f8c770a1f8cb4909bf4a16

### Create contact
POST https://project2-ybyn.onrender.com/movies/ HTTP/1.1
Content-Type: application/json

{
    "title": "The Dark Knight",
    "director": "Christopher Nolan",
    "year": 2008,
    "genre": "Action",
    "rating": 9,
    "actors": "Christian Bale",
    "plot": "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham."

}

### PUT contact
PUT https://project2-ybyn.onrender.com/movies/65f8c770a1f8cb4909bf4a16 HTTP/1.1
Content-Type: application/json

{
    "title": "Schindler's List",
    "director": "Steven Spielberg",
    "year": 1993,
    "genre": "Drama",
    "rating": 8.9,
    "actors": "Liam Neeson",
    "plot": "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazi Germans."
}

### Delete user
DELETE https://project2-ybyn.onrender.com/movies/65f8c770a1f8cb4909bf4a16 HTTP/1.1
